name: Upload Impacted Targets
on: pull_request

jobs:
  compute_impacted_targets:
    name: Compute Impacted Targets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: touch WORKSPACE

      - name: Compute Impacted Targets
        uses: trunk-io/merge-action@3ba10340a57c5067831b3c17b68481bba5aa61b0
        with:
          ### Use your repositories API token to authenticate impacted targets uploads.
          trunk-token: ${{ secrets.TRUNK_REPO_API_TOKEN }}
          verbose: 1
        env:
          API_URL: https://api.trunk-staging.io:443/v1/setImpactedTargets
