name: Upload Impacted Targets
on: pull_request

jobs:
  compute_impacted_targets:
    name: Compute Impacted Targets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: touch WORKSPACE

      - name: Compute Impacted Targets
        uses: trunk-io/merge-action@7c18ac456e31790ea74d3a07a2475c8dcc92d92b
        with:
          ### Use your repositories API token to authenticate impacted targets uploads.
          trunk-token: ${{ secrets.TRUNK_REPO_API_TOKEN }}
          impact-all-filters-path: .trunk/filters.yaml
          verbose: 1
        env:
          API_URL: https://api.trunk-staging.io:443/v1/setImpactedTargets
