filegroup(
    name = "scripts",
    srcs = [
        "compute_impacted_targets.sh",
        "prerequisites.sh",
        "upload_impacted_targets.sh",
    ],
    visibility = ["//tests:__subpackages__"],
)
