filegroup(
    name = "lib",
    srcs = ["foo.txt"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all_files",
    srcs = glob(["*"]),
    visibility = ["//visibility:public"],
)
