name: Pull Request
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Run Tests
        run: |
          pnpm install
          pnpm test
