name: Pull Request
on: [pull_request]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      repository-projects: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        # trunk-ignore(semgrep/yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha)
        uses: trunk-io/trunk-action@v1
