name: Upload Impacted Targets
on: pull_request

jobs:
  compute_impacted_targets:
    name: Compute Impacted Targets
    runs-on: ubuntu-latest
    steps:
      - name: Compute Impacted Targets
        uses: trunk-io/merge-action@176d9f118db4bd447e02dc43b9ed989be0a58372
        with:
          ### Use your repositories API token to authenticate impacted targets uploads.
          trunk-token: ${{ secrets.TRUNK_REPO_API_TOKEN }}
          target-branch: ${{ env.TARGET_BRANCH }}
          bazel-workspace-path: ${{ env.BAZEL_WORKSPACE_PATH }}
          verbose: ${{ env.VERBOSE }}
          bazel-startup-options: ${{ env.BAZEL_STARTUP_OPTIONS }}
